version: "2"
services:
  ackee:
    # image: electerious/ackee
    build: .
    container_name: ackee
    restart: always
    ports:
      - "3000:3000"
    environment:
      - AWS_DEFAULT_REGION=us-east-2
    env_file:
      - .env
    volumes:
      - .:/srv/app:rw
  ddb:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath .
    container_name: ddb
    ports:
      - "8000:8000"
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html
